### ISSUE TITLE
Create list of problems CNS solves

### ISSUE THREAD

**Issue by okwme** [tendermint/spn#101]
> There should be a clear write up of the problems that the chain registry sets out to solve. There seems to me that there are a couple i.e. connocalizing chains, signing security to validators (by ensuring chain uniqueness), promote awareness of chains and ease of use to validators, wallets and nodes by signalling trusted endpoints. This might help narrow down the scope and identify what should be part of the primary phase and what can be added later in secondary and tertiary phases.

**Comment by fadeev** [comment]
Thank you for your comments, Billy! After the last call, we have tried to incorporate feedback into our design and realized that there will be at least three phases. We’ll go over them on the next call, but the objectives of the first one are:

* Maintain uniqueness of chain IDs in the interchain by keeping a registry of unique chain names and associated information and creating rules by which ownership is assigned. From Tendermint docs: “This must be unique for every blockchain. If your testnet blockchains do not have unique chain IDs, you will have a bad time.”
* Let users of Cosmos Hub identify the sources of tokens transferred through IBC by mapping unique chain IDs to IBC clients and allowing designated accounts to manage information about IBC clients.
* Let node operators (validators, full-nodes, etc.) access reliable information about seed nodes that they can use to connect to blockchains.

**Comment by lubtd** [comment]
Moved to https://github.com/tendermint/cns
