### ISSUE TITLE
Disambiguation: x/genesis -> x/launch

### ISSUE THREAD

**Issue by faddat** [tendermint/spn#113]
launch is less confusing than re-using the word genesis everywhere, let's use it!

**Comment by fadeev** [comment]
I agree that `genesis` might not be the best name. Maybe something with launching? `stellarnursery` is too much.

**Comment by lubtd** [comment]
I think we should stick to an explicit name related to the involved feature. Why not simply `launch`? We already do this distinction in the module itself with the naming `LaunchInformation` since the information to launch the chain is not only the genesis but the peers

**Comment by fadeev** [comment]
@lubtd I agree!

**Comment by faddat** [comment]
Yep, launch works great.

**Comment by lubtd** [comment]
Thanks for the issue @faddat, we agreed to rename it
