### ISSUE TITLE
Create chain with a custom genesis

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#115]
Currently, when a chain is created, no information is stored about the genesis, the default genesis generated by the command of the binary is used by validators.
We should let the coordinator being able to provide a custom genesis.
Having the data on-chain is too extensive. The same as `sourceURL`, we should be able to provide a `genesisURL` that points to a json file of the original genesis.

**Comment by faddat** [comment]
Recommend that it be a URL like this one:

QmPrwVpwe4Ya46CN9LXNnrUdWvaDLMwFetMUdpcdpjFbyu

**Comment by lubtd** [comment]
This is actually a case where using IPFS or any other content-addressed file system can be relevant.

For some coordinators, using Github or centralized services could still be preferable for simplicity. I think we can store the hash on-chain anyway so that it can be verified by the validators, I don't know if the "censorship resistance" capability of IPFS is necessary here. Though we can still have a structure that supports different type of URL: `{urlType: "ipfs", url: "Qm..."}`

**Comment by gamarin2** [comment]
Yeah storing the hash is necessary
