### ISSUE TITLE
chore: use hex representation of genesis hash

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#131]
to make them human readable. (64 bytes)

https://github.com/tendermint/spn/blob/7c451f9fe1b573cfcef915c5ce88fc9c140cbc63/x/launch/types/genesis_url.go#L44-L47

**Comment by lubtd** [comment]
Is this one good for you: https://github.com/tendermint/spn/blob/645c4ac0e480bac1d941067c17a67bfb572515f0/x/launch/types/genesis_url.go#L47

So the hash is like `yrGv8wotKfNWqrscp8/h6aMVT5oU1si7/clZF79pmh4=`

**Comment by lubtd** [comment]
Updated to hex

**Comment by ilgooz** [comment]
perfect, thank you!
