### ISSUE TITLE
Use binary encoding for integer values

### ISSUE THREAD

**Issue by dshulyak** [tendermint/spn#137]
I spotted that in some cases we are encoding integers to binary as `[]byte(strconv.Atoi(val))` this is not a correct approach, and should be replaced with a `binary.LittleEndian/BigEndian` encoding or Varint encoding if it is more appropriate.

**Comment by lubtd** [comment]
Thanks for reporting the issue.

This is particularly true for proposal ID encoding. We need to encode them using `BigEndian` to have the proposals correctly indexed in the store.
We use this when scaffolding a basic type with Starport: https://github.com/tendermint/starport/blob/d5fd8f83d2e3d7df49d6a5f79187a5bfc2b3d492/starport/templates/typed/stargate/component/x/%7B%7BmoduleName%7D%7D/keeper/%7B%7BtypeName%7D%7D.go.plush#L109

**Comment by dshulyak** [comment]
big endian won't preserve order for signed integers without an additional transformation. any reasons why codebase uses signed?

**Comment by lubtd** [comment]
As far as I remember, there is no particular reason, we must moved to `uint64`, proposal ID is just an incremented ID

**Comment by lubtd** [comment]
Closing since we stop development on Starport Alpha
