### ISSUE TITLE
Reduce proposals retrieval duplication in launch/keeper/grpc_query.go

### ISSUE THREAD

**Issue by dshulyak** [tendermint/spn#138]
The code in `PendingProposal`/`ApprovedProposals`/`RejectProposals` is almost identical, the only real difference is the type of the proposal and can be reduced to a single parameterized method easily.

**Comment by lubtd** [comment]
We may just remove these three lists in the future.
A new structure would store the information from the approved proposals and we can just delete rejected proposals instead of keeping them in the store.
There will be a single pool for the pending proposals.

**Comment by lubtd** [comment]
Closing since we stop development on Starport Alpha
