### ISSUE TITLE
`account` module namespace collides with a default `account` command

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#177]
**Describe the bug**
We have by default an `account` namespace for Cosmos SDK chains to query SDK account from address.
Our module `account` also create a namespace `account` for queries for the modules

**To Reproduce**
```
spnd q

Querying subcommands

Usage:
  spnd query [flags]
  spnd query [command]

Aliases:
  query, q

Available Commands:
  account                  Query for account by address
  account                  Querying commands for the account module
...
```

## Solution

- Renaming the entire module
- Renaming the command namespace for `account` (`spn-account`)

If we go with solution 1, we must do it as soon as possible. Although I don't see any issue for now by renaming it into `spn-account`. If we do this, we must also rename the namespace for `tx`: `spnd tx spn-account` to avoid confusion

**Comment by lubtd** [comment]
We need to investigate if the usage of `account` as a module name can bring further issues

**Comment by fadeev** [comment]
Renaming `account` to `profile` seems like a good solution to me.

**Comment by lubtd** [comment]
Nice idea, I actually like `profile` a lot

I actually never put lot of attention into this but `Account` is a very recurrent term in the Cosmos SDK and it can then make sense to rename the module quickly to avoid future potential collision like here or also confusion with users initiated with Cosmos SDK

**Comment by lubtd** [comment]
We can still merge https://github.com/tendermint/spn/pull/169 when it will be ready, most of the change will be in `app.go` outside of renaming the package and the command namespace

**Comment by fadeev** [comment]
Sounds good!

**Comment by lubtd** [comment]
I checked, `profile` doesn't seem to be something defined in the SDK anywhere

**Comment by lubtd** [comment]
I think we can go for this. In fact renaming a module is not a very extensive process so we can rerenaming again in the future if an objection occur, but that better to have another name now since it seems it's better to move away from `account`

I think we can wait for https://github.com/tendermint/spn/pull/169 since the PR is almost done and we can implement it afterward.
We should not get conflicts with other PRs @Pantani
