### ISSUE TITLE
test: use `<package>_test` as package for tests

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#191]
Use `keeper_test` instead of `keeper` as package name for tests whenever it is possible (eventually we need internal access to the package for good tests) in order to avoid dependency cycle when tests use a third party package like `sample`

**Comment by fadeev** [comment]
Should this also affect how we scaffold chains with Starport (having a separate package for tests)?

**Comment by lubtd** [comment]
I think we should first work on this issue on `spn`, then see the current templates where we can use `foo_test` package for `starport`

Sometime it's mroe convenient to have an internal access to the package to test

**Comment by lubtd** [comment]
Fixed in https://github.com/tendermint/spn/pull/245

I don't think this change is needed for Starport templates. We needed to simplify test for genesis export/import

However, those tests are too customized so that there would be a point to have them in our templates
