### ISSUE TITLE
Investigate on unpacking for `proto.Any` types

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#211]
In #195 we implement `GetDefaultInitialGenesis` and `GetGenesisURL` to get back the original type from the proto any field: https://github.com/tendermint/spn/blob/59fb56c119ee1b4a0ed73bee46ff0da6e4de972f/x/launch/types/chain.go#L12

This method takes as an argument an unpacker to unpack the any type. However this unpacking fails with the `InterfaceRegistry` as unpacker of the module if the cache of the any type is cleared.

We must investigate and find what is the correct unpacker to use to unpack the any field once #195 will be merged

**Comment by Pantani** [comment]
@lubtd can we close this one?

**Comment by lubtd** [comment]
> @lubtd can we close this one?

![image](https://user-images.githubusercontent.com/7040350/127968405-e6b374a0-f5cb-44c7-a573-5ab9fd8cc504.png)

**Comment by lubtd** [comment]
Solved: we use the interface in the unpacking method instead of the implementation type
