### ISSUE TITLE
Verify and validate all request content

### ISSUE THREAD

**Issue by Pantani** [tendermint/spn#232]
Verify and validate all request content interfaces
https://github.com/tendermint/spn/blob/develop/x/launch/types/request_content.go

e.g.:
```go
// RequestContent defines the interface for a request content
type RequestContent interface{
	Validate() error
}

var _ RequestContent = &AccountRemoval{}

// Validate check the AccountRemoval object
func (g AccountRemoval) Validate() error {
	...
	return nil
}
```

**Comment by Pantani** [comment]
@lubtd do you think makes sense to use this validation in the `applyRequest` method?

```go
func applyRequest(
	ctx sdk.Context,
	k Keeper,
	chainID string,
	request types.Request,
) error {
	cdc := codectypes.NewInterfaceRegistry()
	types.RegisterInterfaces(cdc)

	var content types.RequestContent
	if err := cdc.UnpackAny(request.Content, &content); err != nil {
		return spnerrors.Critical(err.Error())
	}

	if err := content.Validate(); err != nil {
		return err
	}

	switch c := content.(type) {
	case *types.GenesisAccount:
	...
}
```

**Comment by lubtd** [comment]
> @lubtd do you think makes sense to use this validation in the `applyRequest` method?
> 
> ```go
> func applyRequest(
> 	ctx sdk.Context,
> 	k Keeper,
> 	chainID string,
> 	request types.Request,
> ) error {
> 	cdc := codectypes.NewInterfaceRegistry()
> 	types.RegisterInterfaces(cdc)
> 
> 	var content types.RequestContent
> 	if err := cdc.UnpackAny(request.Content, &content); err != nil {
> 		return spnerrors.Critical(err.Error())
> 	}
> 
> 	if err := content.Validate(); err != nil {
> 		return err
> 	}
> 
> 	switch c := content.(type) {
> 	case *types.GenesisAccount:
> 	...
> }
> ```

A request should already be validated when it is applied to the store so it should be a critical error in this case
