### ISSUE TITLE
launch: allows to provide a campaign ID to a chain

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#261]
When a chain is created with `MsgCreateChain`. The coordinator can provide a campaign ID.

The coordinator of the chain must be the coordinator of the campaign.

The chainID is appended to the campaignChains list in `campaign` module

**Comment by Pantani** [comment]
Maybe we need to avoid zero values for campaign id. Because we will never know if a campaign was already set for Chain or if the user is trying to set zero for campaign id. Empty values will return  always zero for the campaign ID

**Comment by lubtd** [comment]
> Maybe we need to avoid zero values for campaign id. Because we will never know if a campaign was already set for Chain or if the user is trying to set zero for campaign id. Empty values will return always zero for the campaign ID

Yes, I added the field `hasCampaign` in https://github.com/tendermint/spn/pull/321

We can wait for this PR to be merge to finish this one. It implement `CreateNewChain` method that will automatically add the chain in the chain list of the campaign

**Comment by Pantani** [comment]
Only by avoiding the zero value index can we skip some checks and prevent an extra field. It's more a matter of opinion, but we can reduce the code and logic

**Comment by Pantani** [comment]
also, with a zero campaign index, it's harder to check if the `MainnetAccount` or the `MainnetVestingAccount` has an invariant and it's not associated with a campaign because the default value is always zero

**Comment by lubtd** [comment]
I would personally prefer to keep things simple and intuitive. Starting from 0 is quite a global norm in computer science and then it would make this part a bit counterintuitive especially since the other list starts from 0.

A better solution, if we would like to keep a single field to me, would be to have a `nullable` field with a pointer.

However, having a specific field to describe if the object has this characteristic or not makes it easier to understand and maintain and is not much more expensive.

>  it's harder to check if the MainnetAccount or the MainnetVestingAccount has an invariant and it's not associated with a campaign because the default value is always zero

I would not consider it as an invariant, if they have 0 then their associated campaign is 0. The critical invariant in this part is that the sum of the shares doesn't overflows the `AllocatedShares` of the campaign
