### ISSUE TITLE
campaign: allows to mint vouchers

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#267]
Implement `MsgMintVouchers` that mint new vouchers of the corresponding shares of the campaign to the coordinator address.

`AllocatedShares` is updated

**Comment by lubtd** [comment]
Hey @Pantani, have you started working on this one?

**Comment by Pantani** [comment]
Not yet. I was thinking of getting this for my next task, but it's up to you. I can switch to another one

**Comment by lubtd** [comment]
> Not yet. I was thinking of getting this for my next task, but it's up to you. I can switch to another one

That's fine I started the mainnet initialization issue so I'm busy. I just think it's better to assign oneself a task when we practically start working on it since we have some hours timezone difference

**Comment by lubtd** [comment]
We should first initialize the voucher type so we can work on all voucher related tasks in parallel: https://github.com/tendermint/spn/issues/313

**Comment by Pantani** [comment]
Sure! sorry, I was assigned to me before we decided to stop one week SPN, after I forgot to remove
