### ISSUE TITLE
Simulation test (`campaign`): failing `MsgSend` operation

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#358]
Depends on https://github.com/tendermint/spn/pull/350
In simulation tests of the campaign module, we define an operation that simulates the `MsgSend` from `bank`. This allows to move the vouchers into different accounts in the simulation environment and therefore we have a higher entropy on the simulation (otherwise the voucher owners are only the coordinators or the entities that call `MsgUnredeemVouchers` after getting shares through `MsgAddShares`)

The message operation always fail in the current simulation and we should figure out why and make successful `MsgSend`

**Comment by giunatale** [comment]
I think this is actually a mistake in the way we are interpreting the simulation report.

While failed simulations are included in the `campaign` report, success transfers are added to the `bank` count.
I've verified this empirically and I can see some sends generated from there are indeed succeeding.

I suggest we change line https://github.com/tendermint/spn/blob/develop/x/campaign/simulation/simulation.go#L349 to use `banktypes.ModuleName` so failures are properly reported under `bank` to not create confusion

<img width="130" alt="image" src="https://user-images.githubusercontent.com/12249307/163417745-a1cc3879-4735-4dc1-9feb-6a69db691fbc.png">
