### ISSUE TITLE
Can't install `spnd` with `curl`

### ISSUE THREAD

**Issue by fadeev** [tendermint/spn#373]
```
~ % curl https://get.starport.com/tendermint/spn@latest! | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    39  100    39    0     0     18      0  0:00:02  0:00:02 --:--:--    18
Release tag latest not found
```

**Comment by lubtd** [comment]
The `latest` release done by the CI is marked as "draft", don't know if it could be related https://github.com/tendermint/spn/releases

**Comment by lubtd** [comment]
Can you test it again now? It works for me

**Comment by fadeev** [comment]
Ok, interesting, it works now. Maybe when CI is running, artifacts get deleted and installation doesn't work. Not sure, but this is not actionable right now.
