### ISSUE TITLE
Support Config file for initial genesis

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#395]
We currently support two different initial genesis types for a chain launch

- `DefaultInitialGenesis`: the default genesis of the chain (from all default genesis state of modules)
- `GenesisURL`: a URL containing a genesis file

`GenesisURL` is practical to use when dumping the state of a previous chain but if the user simply want to change some params of some modules, it requires the user from uploading the genesis

We can simplify simple genesis modification by supporting initial genesis through Starport Config

`StarportConfigGenesis` or simply `ConfigGenesis` would use a specified Starport Config file to construct the initial genesis.
This would allow simple params modification:
```
genesis:
  app_state:
    staking:
      params:
        bond_denom: "spn"
```

We should store the path from the source directory to the Starport config and the hash of the genesis file. Source information is already stored in `Chain`
```
message ConfigGenesis {
  string path = 1;
  string hash = 2;
}
```

**Comment by aljo242** [comment]
What do you mean by storing the path?  It makes sense to load it from a path, but why would we store someone's local path on chain?

**Comment by lubtd** [comment]
We don't need a hash for the config file since the source URL is already associated with a source hash
