### ISSUE TITLE
x/launch/add-validator: support proxied peers

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#407]
Here how peer info is received during add validator request:

https://github.com/tendermint/spn/blob/173d2cf/proto/launch/tx.proto#L101

This is the current format for of the peer field: 

```
node-id@tcp_address
```

On Gitpod, or in other environments where establishing a TCP connection isn't allowed, Starport needs to enable a proxy, for Gitpod this would be an HTTP tunnel.

To optionally enable proxies and let the clients know what proxy needs to be used, we need to advance the `peer` field in `MsgRequestAddValidator` into `Peer peer = 6;` where `Peer` is:

```proto
message Peer {
    string id = 1; // e.g.: 7786ace6ddb3d771024792a46540c88587e0e8cc

    oneof connection {
        string tcpAddress = 2;  // use a TCP address
        HTTPTunnel httpTunnel = 3; // or use an HTTP tunnel
    }

    message HTTPTunnel {
        string name = 1;  // e.g.: chisel (https://github.com/jpillora/chisel)
        string address = 2;  // for chisel running on Gitpod, e.g.: https://3475-chocolate-capybara-kkiztq32.ws-eu21.gitpod.io/
    }
}
```

**Comment by lubtd** [comment]
Seems good

**Comment by Pantani** [comment]
I have a doubt whats is the best way to put the peer parameters into the CLI parameter.

- We can use in this way, if we define a peer name we automatically add the as a HTTP tunnel
```shell
spnd tx request-add-validator [launch-id] [gentx-file] [consensus-public-key] [self-delegation] [peer-address] [peer-name]
```
and if we don't pass we are using the normal peer address
```shell
spnd tx request-add-validator [launch-id] [gentx-file] [consensus-public-key] [self-delegation] [peer-address]
```

- Another way is create a new CLI arg called `is-tunnel`. 
```shell
spnd tx request-add-validator [launch-id] [gentx-file] [consensus-public-key] [self-delegation] [is-tunnel] [peer-address] [peer-name]
```

- And the best way for me is create the `peer-tunnel` flag, and pass the tunnel name:
```shell
spnd tx request-add-validator [launch-id] [gentx-file] [consensus-public-key] [self-delegation] [peer-address] --peer-tunnel  [peer-name]
```

**Comment by lubtd** [comment]
> And the best way for me is create the peer-tunnel flag, and pass the tunnel name:
```
spnd tx request-add-validator [launch-id] [gentx-file] [consensus-public-key] [self-delegation] [peer-address] --peer-tunnel  [peer-name]
```

I think this one is the best. I would name `--peer-tunnel` flag `--http-tunnel` though
Keep in mind that the `spnd` CLI will be mainly used for debugging, or for very advanced users. Having less intuitive commands is less an issue as long as these are simple to use and test all options
