### ISSUE TITLE
Implement `CheckValidatorSet`

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#436]
`CheckValidatorSet` verifies from a `tmtypes.ValidatorSet` https://github.com/tendermint/tendermint/blob/master/types/validator_set.go if the validator set is valid from the information 
stored for the launch of the chain

The method must fail if the launch has not been triggered

**Comment by Pantani** [comment]
I un-assign the task to wait for the #449 merged, and I went back to this task

**Comment by lubtd** [comment]
We should normally be able to implement this method independently from #449

**Comment by Pantani** [comment]
sorry, I put the wrong number, is this one #443. I need to use the same methods to convert the validator to the `ValidatorSet`

**Comment by lubtd** [comment]
Yes sorry I haven't realized it wasn't the same task but we should be able to implement it without #443 because we can use the type `tmtypes.ValidatorSet` https://github.com/tendermint/tendermint/blob/master/types/validator_set.go. This type should be used to access the `.PubKey.Address()` method
Then in `MsgCreateClient` we can use `ToTendermintValidatorSet()` method
