### ISSUE TITLE
Complete implementation for `MsgCreateClient` handler

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#449]
Depends on: https://github.com/tendermint/spn/pull/443 and https://github.com/tendermint/spn/issues/436

Once the message handle is fully implemented we must add tests for it

These tests must absolutely ensure that no spoofing is possible for monitoring IBC connection

**Comment by Pantani** [comment]
I un-assign the task to wait for the #449 merged, and I went back to this task
