### ISSUE TITLE
Add `metadata` field to `Chain` object

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#515]
Add a generic `[]byte` metadata field to the chain definition

This field should have a maximum length

The metadata can be provided from `MsgCreateChain` and edited in `MsgEditChain`

The metatada is fully generic on-chain. Client can provide and interpret a JSON object

**Comment by aljo242** [comment]
How should we handle having a maximum length?  I don't think this really makes sense to be an on-chain param, but I'm not sure what a good value should be.
