### ISSUE TITLE
Collapse `MinLaunchTime` and `MaxLaunchTime` params into single struct

### ISSUE THREAD

**Issue by giunatale** [tendermint/spn#525]
As of now these two parameters are handled as separate. This also means any of the two can be updated independently.
Although in principle this is a good thing, it also prevents from making sure the two values that define the range are always consistent, *i.e.* it could be that `minLaunchTime` > `maxLaunchTime` and this would not be caught, leading to potential dangerous consequences.

We should collapse the two values into a single `range` struct that is updated as a single object. This would make possible to enforce consistency of the range, similarly to what was done for [`campaign`](https://github.com/tendermint/spn/pull/524) with `MinTotalSupply` and `MaxTotalSupply`.

**Comment by lubtd** [comment]
One addition that could be implemented for this PR

Based on the comment I left https://github.com/tendermint/spn/pull/523#discussion_r808449384

I think it can make more sense to use `int64` for the values since they are manipulated with UNIX timestamp and `int64` conversion has vulnerabilities. Positive check can simply be performed in the validate method

**Comment by aljo242** [comment]
I will change the `RevertDelay` param to `int64` and add the positive check for it in #523.  Modifying the remaining params can be based of these changes

**Comment by lubtd** [comment]
We can also simplify `type/genesis_test.go` for params test cases
Since, param `Validate` is fully tested, we only need a valid and invalid param test case for geneses validate tests

https://github.com/tendermint/spn/pull/524#discussion_r809220998

**Comment by giunatale** [comment]
are the gogoproto `yaml` annotations needed for anything in `launch/params.proto`? Can I remove them while addressing this issue?

**Comment by lubtd** [comment]
> are the gogoproto yaml annotations needed for anything in launch/params.proto? Can I remove them while addressing this issue?

I think we initially had them because we thought we needed them for the simulation but we use `json` for the simulation finally
