### ISSUE TITLE
launch: rpc panic

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#536]
I'm testing with 4 validators.

```
root@starport-network-test-4:~# starport n --nightly chain launch 50
rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic
```

**Comment by lubtd** [comment]
What is the command being run?
Is it for `MsgTriggerLaunch` to `spn` or a command sent to the chain being launched? (because afaik `chain launch` simulate the launch of the chain from the current genesis)

**Comment by ilgooz** [comment]
It was `starport n --nightly chain launch 50`

**Comment by ilgooz** [comment]
Can you please try with two Gitpod nodes. I started get this every time when run "launch".
