### ISSUE TITLE
Create `CampaignCreationFee` param

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#538]
Add a `CampaignCreationFee` as param in the`campaign` module

This param would be `EmptyCoin`s by default

If a value is defined, a fee is transferred from the coordinator account and set to the... community pool?

**Comment by giunatale** [comment]
couple questions, valid also for #537:

- are we using a `sdk.Coin` or `sdk.Coins`? - I assume from #537 it is `sdk.Coins`
- I couldn't find a `EmptyCoins` (`EmptyCoin`?), where would it be best defined? I see `campaign` for instance has a `shares.go` where `EmptyShares` is defined.

**Comment by lubtd** [comment]
Yes, for `Chain` and `Campaign` it would be `sdk.Coins`. `EmptyCoins` is just a placeholder here that mean the fee is zero. You can initialize a empty coin with `sdk.NewCoins()`

**Comment by giunatale** [comment]
What's the best course of action to deal with the communityPool?
I was thinking of adding the `distribution` keeper to the module and use [`distrKeeper.FundCommunityPool()`](https://github.com/cosmos/cosmos-sdk/blob/master/x/distribution/keeper/keeper.go#L171).

Is there a better way that you guys are aware of?
