### ISSUE TITLE
Create MaxMetadataLength param

### ISSUE THREAD

**Issue by aljo242** [tendermint/spn#541]
Currently, the maximum length of a metadata field is hard coded [here](https://github.com/tendermint/spn/blob/develop/pkg/types/metadata.go).  It makes more sense to have this as an on chain param.

An issue here is that both the `launch` and `campaign` modules use the metadata field.  Params are stored per-module, but I think the ideal behavior here is that we have a singular MaxMetadataLength param shared by all modules.  

Currently, this can be done by storing the param in one of the modules (say, `campaign`) and then accessing the param from the other module (`launch`) using its keeper.

**Comment by lubtd** [comment]
I put it `on-hold` for now. We should first see the usage of metadata, and see if it makes sense to put it as param
