### ISSUE TITLE
TotalSupplyRange Simulation Param Change Fails

### ISSUE THREAD

**Issue by aljo242** [tendermint/spn#553]
**Describe the bug**

The RandomizedParamChange in the simulation package for the TotalSupplyRange param causes a fail when the simulation parameters are changed a bit.

```shell
[2022-02-22|10:31:21.029] attempt to set new parameter value; key: totalsupplyrange, value: "minTotalSupply:"100" maxTotalSupply:"1000000000000000" " module=x/params 
    simulate.go:300: error on block  1/2000, operation (16/37) from x/gov:
        failed to execute message; message index: 0: key: totalsupplyrange, value: "minTotalSupply:"100" maxTotalSupply:"1000000000000000" ", err: invalid character '1' after top-level value: failed to set parameter: invalid proposal content [cosmos/cosmos-sdk@v0.44.6/x/gov/keeper/proposal.go:24]
        Comment: unable to deliver tx
```

**To Reproduce**

Run `starport chain simulate` with the following modifications made to `app/simulation_test.go`:

```go
func BenchmarkSimulation(b *testing.B) {
	simapp.FlagEnabledValue = true
	simapp.FlagNumBlocksValue = 2000
	simapp.FlagBlockSizeValue = 100
	simapp.FlagCommitValue = true
	simapp.FlagPeriodValue = 10
	simapp.FlagVerboseValue = true
```

**Please provide output of commands**
 - `spnd version`: latest-2c5f4556
 - `go version`: go version go1.17.7 linux/amd64
 - `uname -a`: Linux cozart-dev 5.16.10-arch1-1 ... x86_64 GNU/Linux

**Comment by giunatale** [comment]
I think that might be due to https://github.com/tendermint/spn/blob/develop/x/campaign/module_simulation.go#L58. I have likely made a mistake on the format
