### ISSUE TITLE
Investigate on removing accounts and validators

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#63]
We can either implement a way to reject already approved proposal with an new additional check to see if an approved proposal can be rejected based on the state of the chain (for example cannot reject an approved account if there is an approved validator related to it).
-> May be a costly check for certain proposal and so we may introduce a new property to make some type of proposal "unrejectable"

Or consider that an approved proposal can never be rejected in the future and therefore implement specific proposals like `ProposalRemoveAccount` and `ProposalRemoveValidator`

**Comment by ltacker** [comment]
We could consider `ProposalUpdateAccount` and `ProposalUpdateValidator` as well

**Comment by lubtd** [comment]
Closing since we stop development on Starport Alpha
