### ISSUE TITLE
Add a `CampaignSummaries` query

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#642]
Names of the query and fields are open for suggestion

`CampaignSummaries` allows getting with a single query an overview of the state of campaigns that give more thorough information than the simple `AllCampaign` query

The information that we would like to list:
```
campaignID
coordinator
totalSupply
allocatedShares
metadata
mostRecentChainLaunchID if any
mostRecentChainRewardPool if any
mostRecentChainNumberOfRequests if any
mostRecentChainNumberOfValidators if any
```

Anything to add, any suggestions? @fadeev

**Comment by fadeev** [comment]
To clarify what @JoseRFelix said, we need `mostRecentChainSourceURL` and `mostRecentChainSourceHash`.

**Comment by fadeev** [comment]
We'll also need the most recent chain's metadata, I believe.

**Comment by lubtd** [comment]
We can address it today

**Comment by lubtd** [comment]
Do we agree on the query name `CampaignSummaries`? @JoseRFelix @fadeev 

Or any other suggestion?

**Comment by fadeev** [comment]
"Campaign details", instead?

**Comment by JoseRFelix** [comment]
I think I prefer `CampaignSummaries` since it represents an overview of the data. I feel like `CampaignDetails` would give me extra information that could be used on a campaign individual page
