### ISSUE TITLE
Nondeterminism detected in simulation tests

### ISSUE THREAD

**Issue by aljo242** [tendermint/spn#659]
Running `make test-sim-nondeterminsim` on `develop` yields the following result:

```shell
 Error Trace:    simulation_test.go:197
                Error:          Not equal: 
                                expected: " \x87D\xa7ͯ(<\x1e@ݫ/+\xee6\x9a\xd2%\x8f\xcfX\xec8\x9fv\xf7ł\xf2\xd7\x1f"
                                actual  : "0\xf27\xaa\xd0\x10\xaf\xf8SFA\x82\x9d#x\xeeK\xe4\x1e\x00F\xb3\x1d\x91<\x92\x05\xbb!\xca(\xa5"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                - �D�ͯ(<@ݫ/+�6��%��X�8�v�ł��
                                +0�7����SFA��#x�K�F��<��!�(�
                Test:           TestAppStateDeterminism
                Messages:       non-determinism in seed 5577006791947779410: 1/3, attempt: 2/5
```

This non-determinism could be due to many issues, but the best case scenario for us is that the issue has to do with how our simulation tests are set up rather than actually having issues in the chain.  I will open issues for possible causes of this behavior and encourage us all to try to investigate.

**Please provide output of commands**
 - `spn version`: `latest-87ee3fc6`
 - `go version`:  `go1.18 linux/amd64`
 - `uname -a`:  `Linux cozart-dev 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux`

**Comment by lubtd** [comment]
I no longer have the AppHash issue if we set `DefaultGenesis` and `DefaultParams` for all `GenerateGenesisState` and `RandomizedParams`

I still got an error
```
Simulating... block 75/100, operation 0/289. Logs to writing to /Users/lucas/.simapp/simulations/2022-03-29_13:42:47.log
    simulate.go:300: error on block  75/100, operation (18/289) from x/launch:
        failed to execute message; message index: 0: campaign with id 8 already associated with chain 78: chain already is associated with a campaign [tendermint/spn/x/launch/keeper/msg_edit_chain.go:44]
        Comment: unable to deliver tx
--- FAIL: TestAppStateDeterminism (5.17s)
```
But it seems to be linked to the `FindChain` method that doesn't correctly check if the chain already has an associated campaign for the message `MsgEditChain`

**Comment by aljo242** [comment]
Yeah, I was also getting this issue before.  It appears there are multiple issues with the simulation testing.  Any minor change to that code will change the path of the simulation, so sometimes you will run into these issues before the sim can complete.  What happens if you run this sim for 50 blocks? (terminating before this error will tell us if there is still an AppHash issue)

**Comment by lubtd** [comment]
I just remove `MsgEditChain` from the simulation and the AppHash problem came back... makes sense if it is compared at the end of the simulation
