### ISSUE TITLE
Add invariant checks to simulations

### ISSUE THREAD

**Issue by aljo242** [tendermint/spn#666]
Our longer running simulations (especially non-determinism) tests exist to fully stress the blockchain, but they currently do not have Invariant checking enabled.

This is an easy addition, as we just have to set a boolean flag in the setup code.  I propose we make this addition to make these tests a bit stronger.

**Comment by lubtd** [comment]
Thanks for raising this, I thought it was enabled by default

**Comment by aljo242** [comment]
Yes, its just changing those two flags.  Then seeing the `Period` flag to some value that causes the invariant checks to be run at that period of blocks.
