### ISSUE TITLE
`MsgSetRewards` and `MsgAddValidatorOperatorAddress` simulation operation always failing

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#667]
Seems the failure rate for both operation is 100% independently of the chosen seed
```
"profile": {
  "add_validator_operator_address": {
   "failure": 49
  },

...

"reward": {
  "set_rewards": {
   "failure": 35
  }
 },
```

**Comment by giunatale** [comment]
the simulation for `set_rewards` and `add_validator_operator_address` are empty. They both contains a `TODO`.
I think we should split this up into two issues and tackle each individually, as their implementation is completely absent.

**Comment by lubtd** [comment]
Ok that why the simulation messages fail...

Yes, we can totally separate the issue `MsgSetRewards` would be a priority for the Milestone. `MsgAddValidatorOperatorAddress` not

**Comment by lubtd** [comment]
Closing in favor of https://github.com/tendermint/spn/issues/704 and https://github.com/tendermint/spn/issues/703
