### ISSUE TITLE
Code coverage - Check up

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#687]
Report of the files where code coverage can potentially be improved
Checked from output in `cover.html` from `make test-cover` command

- Most of the files would only require minimal addition
- Missing tests I consider as high priority are pointed out
- `monitoring_packet` file tests from both monitoring modules would potentially be more complex, implying mocking from IBC

- [x] `campaign`
```
	genesis
	keeper/
		invariant
		total_shares
		grpc_params
	types/
		shares
```
- [x] `launch`
```
	keeper/
		grpc_params
		keeper
		msg_settle_request
		request
		validator_set
	types/
		msg_trigger_launch
		params
		request_content
```
- [x] `monitoringc`
```
	keeper/
		grpc_params
		grpc_verified_client_ids
		handshake
		monitoring_packet - not tested, would eventually be a bigger task for IBC mocking
		msg_create_client
	types/
		genesis - high priority
		params
```
- [x] `monitoringp`
```
	keeper/
		begin_block
		grpc_connection_channel_id
		grpc_consumer_client_id
		grpc_monitoring_info
		grpc_params
		handshake
		monitoring_packet - not tested, would eventually be a bigger task for IBC mocking
```
- [x] `participation`
```
	genesis
	keeper/
		grpc_params
		msg_participate
	types/
		genesis - high priority
		params
```
- [x] `profile`
```
	genesis
	types/
		genesis
```
- [x] `reward`
```
	keeper/
		grpc_params
		msg_set_reward - high priority, code verifying sufficient balance for reward pool is not covered
		reward_distribution
	types/
		genesis - high priority
		reward_pool
```

**Comment by lubtd** [comment]
I will work on `msg_set_reward` and the different `grpc_params` (where we just need a test to handle nil request) @giunatale @aljo242

**Comment by giunatale** [comment]
I can take the remainder of `participation` and `profile`.

**Comment by giunatale** [comment]
I can also take on `campaign`

**Comment by aljo242** [comment]
I will take on `launch` and `reward` to start

**Comment by giunatale** [comment]
@aljo242 I'm taking `monitoringc`, can you take on `reward` and `monitoringp` so we can finish this task?

**Comment by giunatale** [comment]
Eventually we'll do another round of check up, but I suggest we get this done as soon as possible.
