### ISSUE TITLE
`SimulateMsgUpdateTotalSupply` missing in `WeightedOperation` in simulation

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#718]
`SimulateMsgUpdateTotalSupply` is not part of the `WeightedOperation` array in `campaign/module_simulation`

We should add it to simulate the message

Since the message operation call `GetCoordSimAccountWithCampaignID` with arg `requireNoMainnetInitialize` is set to true, we may have the same issue as in https://github.com/tendermint/spn/issues/717

**Comment by giunatale** [comment]
As per my comment to #717, fyi with `make test-sim-ci` we get 5 failures and 6 successes for this msg simulation
