### ISSUE TITLE
proposal: drop rest endpoints

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#73]
I think it's fine to maintain only gRPC API instead of maintaining two APIs that are identical in terms of functionality. There is also gRPC Gateway option that can be adopted by users that prefer the HTTP API.

**Comment by ltacker** [comment]
Remaining REST endpoints are removed in `genesis` in #75
But we need to remove them for `chat` and `identity`

**Comment by lubtd** [comment]
Closing since we'll not maintain `chat` and `identity` anymore
