### ISSUE TITLE
Implement events for `monitoring-consumer` module

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#733]
Implement typed events for the `monitoringc` module based on the different messages of the module. `CreateClient` in this case

Eventually one event when receiving a monitoring packet from the provider but I would think that we already have events for packets in IBC, though having a typed event for the monitoring packet can eventually make sense

**Comment by aljo242** [comment]
This module already emits non-typed events which are defined [here](https://github.com/tendermint/spn/blob/develop/x/monitoringc/types/events_ibc.go).  

These events are reasonable to me, so the only modification we could make is turning them into typed events.  Do we want to go ahead with that, or are these existing events ok?

**Comment by lubtd** [comment]
Then we can close the issue if there are no evident events 👍

Let's see in the future if something is needed for the backend
