### ISSUE TITLE
Implement events for `monitoring-provider` module

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#734]
Implement events for the module if there are events to emit

The module has no message but same as https://github.com/tendermint/spn/issues/733, it could eventually make sense to have an event when the IBC monitoring packet is written

**Comment by aljo242** [comment]
This module already emits non-typed events which are defined [here](https://github.com/tendermint/spn/blob/develop/x/monitoringp/types/events_ibc.go).  

These events are reasonable to me, so the only modification we could make is turning them into typed events.  Do we want to go ahead with that, or are these existing events ok?
