### ISSUE TITLE
Investigate custom block reward distribution

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#738]
Investigate the technical requirements for having a customized distribution of the block rewards

As discussed, I assign it to you @giunatale. You can use this issue or Notion to share research

**Comment by lubtd** [comment]
Hey @giunatale . Can this issue be considered as completed?

**Comment by giunatale** [comment]
Yes, sorry, I am a bit behind with the notes. But this can be closed so I'll do it now.

Generally speaking, the solution to this specific issue is to replicate the same structure of the `mint` module from [osmosis](https://github.com/osmosis-labs/osmosis/blob/main/x/mint/types/params.go#L57), where percentages of the inflation in the block reward is partitioned for different purposes (staking, devs, incentives, comm.pool) by setting module params.
