### ISSUE TITLE
proposal: drop query and tx commands

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#74]
I think there is no need for maintaining CLI commands related to querying and creating/sending txs at this stage. These can be added in future if absolutely necessary. For now, programmatic access looks like enough for our needs.

**Comment by ltacker** [comment]
I personally prefer to keep them, the CLI commands are useful for some local testing and are not hard to maintain since they just directly call the query in `grpc_query.go` with arguments from the command line.
