### ISSUE TITLE
`localnet` network start script fails

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#744]
**Describe the bug**
Starting a local network with 3 validators fail with the error:
```
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x665ec60, 0xc000f252b0}, 0xc00011e748, {0x663a598, 0xc000289180}, {0x663a5e8, 0xc000289370}, {0xc000f61890, 0xb, 0x22}, ...}, ...)
	/Users/lucas/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.3/x/params/types/subspace.go:109 +0x307
github.com/tendermint/spn/x/monitoringp/keeper.Keeper.LastBlockHeight(...)
```

which should normally happen if `LastBlockHeight` param is not set in `genesis.json`
However, this param is actually defined in `genesis_template.json`:
```
    "monitoringp": {
      "params": {
        "lastBlockHeight": "1",
        "consumerChainID": "orbit-1",
        "consumerUnbondingPeriod": "2",
        "consumerRevisionHeight": 1
      },
      "port_id": "monitoringp"
    },
```

**To Reproduce**
1. `ignite c build`
2. `cd localnet`
3. `python3 start.py`

**Please provide output of commands**
 - `spn version`
 - `go version`
 - `uname -a`

**Comment by giunatale** [comment]
are we sure it's the right data type?

shouldn't it be `"lastBlockHeight": 1,` instead of `"lastBlockHeight": "1",`?
