### ISSUE TITLE
Query validator by address

### ISSUE THREAD

**Issue by Matthews3301** [tendermint/spn#755]
**Is your feature request related to a problem? Please describe.**
I would like to query validator by `address` only rather than `launchID` + `address`. This is to be used in Ignite front-end.

In https://github.com/tendermint/spn/blob/develop/proto/launch/query.proto you can find
```
// Queries a genesisValidator by index.
rpc GenesisValidator(QueryGetGenesisValidatorRequest) returns (QueryGetGenesisValidatorResponse) {
  option (google.api.http).get = "/tendermint/spn/launch/genesis_validator/{launchID}/{address}";
}
```

**Describe the solution you'd like**
Would it be possible to also add something like this:
```
// Queries a genesisValidator by address.
rpc GenesisValidator(QueryGetGenesisValidatorRequest) returns (QueryGetGenesisValidatorResponse) {
  option (google.api.http).get = "/tendermint/spn/launch/genesis_validator/{address}";
}
```
This would return an array since sometimes a validator is present in multiple launches.

**Describe alternatives you've considered**
Tried querying RPC directly, however this is not possible.

**Comment by fadeev** [comment]
Since this is not critical for the UI, let's postpone this.

**Comment by fadeev** [comment]
Right now, we can query for all the "add validator" requests with the following query:

https://api.nightly.starport.network/cosmos/tx/v1beta1/txs?events=message.action=%27request_add_validator%27

This, however, only shows requests for all validators.

What we need instead is:

* events to filter all "add validator" request **of a particular validator** that were approved
* events to filter all "remove validator" request **of a particular validator** that were approved

Most likely this is going to use `txs?events=message.action="settle_request"` and we need to add `something.validator_address="spn***"` and `something.request_status="approved"`.

In any case, what this should allow us to do is fetch all approved add validator requests from a particular validator and remove the approved remove validator requests.

**Comment by lubtd** [comment]
Closing as it should be solved by the backend solution
