### ISSUE TITLE
Record datetime of an auction bid

### ISSUE THREAD

**Issue by Matthews3301** [tendermint/spn#801]
**Is your feature request related to a problem? Please describe.**
In Fundraising module, `FundraisingBid` should return time when the bid took place.

**Describe the solution you'd like**
`FundraisingBid` model should have a field `created_at` which records timestamp of the bid.

**Describe alternatives you've considered**
Not using this information.

**Comment by giunatale** [comment]
we don't develop this module, we cannot make changes or additions. You should get in touch with B-Harvest. I am still out @Lucas can you redirect him? Though just as a cautionary statement, they might not be willing to do this, but I might be wrong.

**Comment by giunatale** [comment]
The blocktime of the block where the bid tx got included already has a timestamp, that's why I believe B-Harvest won't be implementing this request. Sorry

**Comment by lubtd** [comment]
A `Bid` is an object in the store, it can still be possible to have a `CreateAt` field in this object. If this is important we can create an issue in `fundraising` to propose the change, I think it would not be an extensive burden to the store
