### ISSUE TITLE
proposal: add Chisel Address on-chain 

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#81]
note: this one doesn't have a priority.

https://github.com/tendermint/starport/pull/467 uses [P2PAddress](https://github.com/tendermint/spn/blob/4919f18f0756ff841ad7b465755919a735df1391/x/genesis/types/types.pb.go#L526) field on chain to keep Chisel URL (when enabled) with a hacky way. Chisel URL is a completely different type of address and not same as Tendermint's P2P addresses (`node-id@url`). 

I think it is better to make Chisel URL a first class member in SPN and keep next to Tendermint's p2p address and let validators to decide on which one to use.

It also would be nice to split `node-id@url` into separate fields as `NodeID` and `nodeAddess` because `nodeID` is also needed by Chisel option.

**Comment by ltacker** [comment]
> It also would be nice to split node-id@url into separate fields as NodeID and nodeAddess because nodeID is also needed by Chisel option.

We can definitely do that, though I would name `NodeAddress` to `NodeURL`.

For storing the Chisel address, I don't really like the fact to store data related to a specific technology while, as a Blockchain, `spn` should only store unbiased data and avoid having a strong coupling with a specific CLI. I would store that data as something more generic like `metadata` as a `string` or `[]byte` so the CLI can interpret on its own

**Comment by lubtd** [comment]
https://github.com/tendermint/spn/issues/407
