### ISSUE TITLE
refactor(types): rm peers from Chain

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#82]
Would it make sense to remove [peers](https://github.com/tendermint/spn/blob/1e2063432c802e022da9f47aad8fc6743276fc80/proto/genesis/v1beta/types.proto#L12) from `Chain` since we already have it in [QueryLaunchInformationResponse](https://github.com/tendermint/spn/blob/1e20634/proto/genesis/v1beta/querier.proto#L77)?

**Comment by ltacker** [comment]
Yes I agree with this change.
Moreover, the chain structure should have static information about a chain while `peers` is related to the launch information

**Comment by lubtd** [comment]
Closing since we stop development on Starport Alpha
