### ISSUE TITLE
feature(grpc): add more chain info to list chains query

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#84]
Right now `QueryListChainsResponse` only returns `chainIDs`.

In order to implement https://github.com/tendermint/starport/issues/479, we need to have more info about each chain when queried with [ListChains](https://github.com/tendermint/spn/blob/1e20634/proto/genesis/v1beta/querier.proto#L11). Instead of accomplishing the same outcome by making individual requests to [ShowChain](https://github.com/tendermint/spn/blob/1e20634/proto/genesis/v1beta/querier.proto#L12) for each chain, I prefer to extend [QueryListChainsResponse](https://github.com/tendermint/spn/blob/1e20634/proto/genesis/v1beta/querier.proto#L24) type like this:
```proto
message QueryListChainsResponse {
	  cosmos.base.query.v1beta1.PageResponse pagination = 1;
	  repeated Chain chains = 2;
}
```

Wdyt?

**Comment by ltacker** [comment]
It used to return only the chain id because it was cleaner and lighter since we had the genesis in the chain information.

If it serves better the CLI with this format, I'm ok with it. With no genesis, the response would not be that heavy.
