### ISSUE TITLE
feature: finalize a chain

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#89]
Implement a message `MsgFinalize` that finalizes (set the `final` attribute of a chain to `true`) the chain is it can be launched.

The message takes a `chainID` and `sender` as a parameter.
The message fail if:
- the chain doesn't exist
- `sender` is not `coordinator`
- the chain is already finalized

Once a chain is finalized no new proposals can be created, rejected, or approved
If a chain is not finalized the the `LaunchInformation` query fails to prevent launching a non-finalized chain. Then any validator can launch the command `starport network chain start` without wondering if the chain can be launch, the command will fail if the chain is not finalized, and it will try to connect to peers if the chain is finalized

**Comment by fadeev** [comment]
This seems like a good idea, but I'm not sure about requiring the coordinator to execute an additional command. Isn't `timestamp` in genesis supposed to serve as the date, before which the blockchain won't start. Maybe we just allow the coordinator to pass an optional flag to set the launch date (current date by default).

**Comment by ltacker** [comment]
Yes, we can do this as well. It just we have less control over it since we can't predict how long the genesis construction process will take.

An advantage with defined genesis time is that it's already more decentralized (but it's not really relevant for now since the coordinator can decide everything concerning proposals anyway)

**Comment by lubtd** [comment]
@fadeev forgot to talk about it during our call. Wouldn't be chain "finalization", explicitly knowing when validators can start their chain, an issue we should address for the Manual Launch milestone?

**Comment by fadeev** [comment]
It's a lower priority item, than others, but it might be useful.

**Comment by lubtd** [comment]
Closing since we stop development on Starport Alpha
