### ISSUE TITLE
`Chain` structure: add the ability to impose the account balance to be requested

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#927]
**Is your feature request related to a problem? Please describe.**
When launching a testnet, the purpose of the account is to have some tokens to interact with the chain, performing a self-delegation fo a validator, etc... tokens has no monetary values and there is no interest for an account to have more tokens than other accounts

Letting accounts request more tokens can be dangerous if a coordinator approve by mistake an account with 10x more tokens for example and the validator end up with the ability to self-delegate more than 1/3 of the supply. This can be particularly dangerous for incentivized testnet.

**Describe the solution you'd like**
In `MsgCreateChain` and `Chain` structure, adding an option for account to impose a specific balance.

Example:
```
Chain:
  AccountBalance: sdk.Coins
```

Applying an `AddGenesisAccount` or `AddVestingAccount` automatically use this value for the account balance

**Comment by aljo242** [comment]
I think `DefaultAccountBalance` is a bit clearer
