### ISSUE TITLE
upgrade to Cosmos SDK 0.40.0

### ISSUE THREAD

**Issue by ltacker** [tendermint/spn#99]
Upgrade with the new stable version of Cosmos SDK Stargate.

Note from Helder:
We must update the `gentx` command in https://github.com/tendermint/spn/blob/develop/.ansible/roles/cosmos-node/tasks/main.yml#L130 with the new command interface.

**Comment by ilgooz** [comment]
I think this can be considered as a high priority now, for  `starport relayer` to work with SPN.

**Comment by ilgooz** [comment]
Btw, gentx is already made compatible with different versions of Stargate.
